grademate/src/app/login/login.component.html

add content in login component that need in the main branch

add content in login component

---

grademate/src/app/signup/signup.component.css
grademate/src/app/signup/signup.component.html

i updated the css style in sign up form

modify some changes in sign up form

---

grademate/src/app/app.module.ts
grademate/src/app/password-recovery/password-recovery.component.html

i added password-recovery folder

add password-recovery folder

---

grademate/src/app/app.component.html
grademate/src/app/login/login.component.html
grademate/src/app/password-recovery/password-recovery.component.css
grademate/src/app/password-recovery/password-recovery.component.html
grademate/src/app/password-recovery/password-recovery.component.spec.ts
grademate/src/app/password-recovery/password-recovery.component.ts

modify some changes in password-recovery file

modify some changes in password-recovery

---

grademate/src/app/app.module.ts
grademate/src/app/dashboard/dashboard.component.html
grademate/src/app/dashboard/dashboard.component.spec.ts
grademate/src/app/dashboard/dashboard.component.ts

I added dashboard folder that need in the main branch.

add dashboard folder

---

grademate/src/app/app.component.ts
grademate/src/app/app.module.ts
grademate/src/app/login/login.component.ts
grademate/src/app/signup/signup.component.ts

I modify some changes in our repo so please review it.

modify some changes

---

grademate/src/app/app.component.html
grademate/src/app/login/login.component.css
grademate/src/app/login/login.component.html
grademate/src/app/login/login.component.ts
grademate/src/app/signup/signup.component.css
grademate/src/app/signup/signup.component.html
grademate/src/app/signup/signup.component.ts
grademate/src/styles.css

Updated the login and signup files. Also, I updated the routing to prevent component lost

update login and signup

---

grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.html

i added some changes in dashboard

modify some changes in dashboard

---

grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.html

I updated dashboard css and modify dashboard html line that exceeded 80 columns.

update dashboard css and modify exceeded 80 columns

---

grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.html
grademate/src/app/login/login.component.css
grademate/src/app/signup/signup.component.css
grademate/src/styles.css

update login, signup and dashboard html and css

update login, signup and dashboard

---

grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.html
grademate/src/app/dashboard/dashboard.component.ts

Goodevening guys! I update the css styles in our dashboard component css. Please review it, thank you.

update css style in dashboard file

---

grademate/src/app/login/login.component.css
grademate/src/app/signup/signup.component.css

I update the login and signup css file.

update the login and signup css

---

grademate/src/app/dashboard/dashboard.component.html
grademate/src/app/dashboard/dashboard.component.ts

modify some changes for grade entry in dashboard

modify some changes in dashborad in grade entry

---

grademate/src/app/dashboard/dashboard.component.css

I added some changes in Dashboard

add some changes in dashboard

---

grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.html

I updated the dashboard css for the clean layout of our dashboard. Please review it.

update the dashboard css

---

grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.html

I update the dashboard css file and dashboard html file.

update the dashboard css file and fix the lines that exceeded 80 columns

---

grademate/src/app/dashboard/dashboard.component.css

I update the color of the table container and modal content in dashboard.

update the color of css in dashboard

---

grademate/src/app/about-us/about-us.component.css
grademate/src/app/about-us/about-us.component.html
grademate/src/app/about-us/about-us.component.spec.ts
grademate/src/app/about-us/about-us.component.ts
grademate/src/app/app-routing.module.ts
grademate/src/app/app.component.html
grademate/src/app/app.component.ts
grademate/src/app/app.module.ts
grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.ts
grademate/src/app/faqs/faqs.component.css
grademate/src/app/faqs/faqs.component.html
grademate/src/app/faqs/faqs.component.spec.ts
grademate/src/app/faqs/faqs.component.ts
grademate/src/app/footer/footer.component.css
grademate/src/app/footer/footer.component.html
grademate/src/app/footer/footer.component.spec.ts
grademate/src/app/footer/footer.component.ts
grademate/src/app/header/header.component.css
grademate/src/app/header/header.component.html
grademate/src/app/header/header.component.spec.ts
grademate/src/app/header/header.component.ts
grademate/src/app/home/home.component.css
grademate/src/app/home/home.component.html
grademate/src/app/home/home.component.spec.ts
grademate/src/app/home/home.component.ts
grademate/src/styles.css

Goodafternoon guys! I added some components which is home, about-us, faqs, header and footer. I already route it. Please review it, thankyou.

Added some components which is home, about-us, faqs, header and footer.

---

grademate/src/app/about-us/about-us.component.css
grademate/src/app/faqs/faqs.component.css
grademate/src/app/home/home.component.css
grademate/src/app/home/home.component.html

I added some content in our homepage. Please review it, thank you.

add a content in homepage

---

grademate/src/app/login/login.component.css
grademate/src/app/login/login.component.html
grademate/src/app/login/login.component.ts

I added an alert if the user input the wrong gmail, the error message pop and it will say "Invalid format". I also added "This field is required" for validation feedback of the user input.

add an alert in login component

---

grademate/src/app/dashboard/dashboard.component.html
grademate/src/app/header/header.component.html
grademate/src/app/home/home.component.html
grademate/src/app/login/login.component.css
grademate/src/app/login/login.component.html
grademate/src/app/signup/signup.component.css
grademate/src/app/signup/signup.component.html
grademate/src/index.html
grademate/src/styles.css

I removed the page headers in login, signup, and dashboard html as per sir steven instructions. Please review it, thank you.

remove the page headers in login, signup, and dashboard html

---

grademate/src/app/header/header.component.css
grademate/src/app/header/header.component.html
grademate/src/app/login/login.component.html
grademate/src/app/signup/signup.component.html

Goodevening guys! I updated the login and signup html. Also, I fix the lines that exceeded 80 columns.

update the login and signup component and fix the 80 columns

---

grademate/src/app/dashboard/dashboard.component.css

modify some changes of CSS in dashboard

add some changes in dashboard.component.css

---

grademate/grademate_db/assessment.php
grademate/grademate_db/authMiddleware.php
grademate/grademate_db/course.php
grademate/grademate_db/courses.php
grademate/grademate_db/database.php
grademate/grademate_db/login.php
grademate/grademate_db/registration.php
grademate/grademate_db/session_check.php

add new php files and update some backend

Deployment

---

grademate/src/app/dashboard/dashboard.component.html
grademate/src/app/dashboard/dashboard.component.ts

Good afternoon guys, I already update the assessment section so that when the user click the button of assessment type it can add the rows, type in the table, and navigate the arrow keys. Please review it, thank you.

modify the assessment section

---

grademate/src/app/dashboard/dashboard.component.css
grademate/src/app/dashboard/dashboard.component.html
grademate/src/app/dashboard/dashboard.component.ts

modify some changes of  Logout in dashboard

add some changes of logout in dashboard

---

grademate/src/app/dashboard/dashboard.component.ts

changes in assessment in dashboard.component.ts

modify some changes in assessment

---

grademate/package-lock.json
grademate/package.json
grademate/src/app/footer/footer.component.html

I added some changes in Footer.

add some changes in footer

---

grademate/src/app/dashboard/dashboard.component.html

fix 80 columns
